server:
  port: 8089

chroma:
  base-url: http://localhost:8000

openrouter:
  api-key: ${OPENROUTER_API_KEY}
  base-url: https://openrouter.ai/api/v1
  chat-model: google/gemini-2.5-flash

huggingface:
  api-key: ${HF_API_KEY}
  base-url: https://router.huggingface.co/v1
  embedding-model: BAAI/bge-small-en-v1.5
