# Shared Defaults for all Questly Microservices
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-value: ${JWT_PUBLIC_KEY}

  # Database Connections Default (Individual service overrides only database name)
  datasource:
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
    # Spring Boot JPA Default setup
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: false

  # Redis Default Connection Properties
  data:
    redis:
      host: localhost
      port: 6379

# JWT RS256 Token Configuration Parameters
auth:
  jwt:
    # 2048-bit RSA Private Key base64 string for token signing
    private-key: ${JWT_PRIVATE_KEY}

# Actuator Management Default
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
