server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/db_assignment
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

ai-service:
  base-url: ${AI_SERVICE_BASE_URL:http://ai-service:8089}

course-service:
  base-url: ${COURSE_SERVICE_BASE_URL:http://course-service:8086}
