server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_auth
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:local-dev-placeholder}
            client-secret: ${GOOGLE_CLIENT_SECRET:local-dev-placeholder}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            issuer-uri: https://accounts.google.com

auth:
  jwt:
    access-token-expiry-seconds: 900   # 15 minutes
    refresh-token-expiry-days: 7
