server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_flashcard
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

ai-service:
  base-url: http://localhost:8089
