server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-value: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA66uo527cR+Bp9G4xz3+q
            O+DFVmgYPpTmIguoEDP8Xom7pBWLc+OQLqkOvyS567G7qvhraKYBgVGOZmJOq+oz
            0rRa8/uB4k/DhylCBTT6odbnoU8Tb4fIWymhcFS20XqIJuIlxW3DXHKtGuAAhMSk
            ZatOVVjbrMY3geI/DNek2Hbec03zPXN1NQW80Si9hLKo5AO7eyXKT9UFcBxvmM5w
            94ZnaBQXxF66kMTn4IFje1wc0r//3eNWsxNBJTmn28eKqYYs1NE1b6rB/D1AKU6a
            Be09uJwxSrDZc7Rzezdf6jAuxxZw0mRtGgrgZv6HeI/Ci07wdsYmKXoHs6L+aZ21
            EQIDAQAB
            -----END PUBLIC KEY-----

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: notebook-service
          uri: lb://notebook-service
          predicates:
            - Path=/api/notebooks/**
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/quizzes/**
        - id: flashcard-service
          uri: lb://flashcard-service
          predicates:
            - Path=/api/flashcards/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
        - id: assignment-service
          uri: lb://assignment-service
          predicates:
            - Path=/api/assignments/**
        - id: practice-service
          uri: lb://practice-service
          predicates:
            - Path=/api/practice/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
        - id: gamification-service
          uri: lb://gamification-service
          predicates:
            - Path=/api/gamification/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
