server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_notebook
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: documents

ai-service:
  base-url: http://localhost:8089
