# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import identity_service_pb2 as identity__service__pb2
except ImportError:
    from shared.grpc import identity_service_pb2 as identity__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in identity_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsersBatch = channel.unary_unary(
                '/identity.IdentityService/GetUsersBatch',
                request_serializer=identity__service__pb2.BatchUserRequest.SerializeToString,
                response_deserializer=identity__service__pb2.BatchUserResponse.FromString,
                _registered_method=True)
        self.GetUserByEmail = channel.unary_unary(
                '/identity.IdentityService/GetUserByEmail',
                request_serializer=identity__service__pb2.UserByEmailRequest.SerializeToString,
                response_deserializer=identity__service__pb2.UserResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetUsersBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsersBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersBatch,
                    request_deserializer=identity__service__pb2.BatchUserRequest.FromString,
                    response_serializer=identity__service__pb2.BatchUserResponse.SerializeToString,
            ),
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=identity__service__pb2.UserByEmailRequest.FromString,
                    response_serializer=identity__service__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identity.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('identity.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsersBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.IdentityService/GetUsersBatch',
            identity__service__pb2.BatchUserRequest.SerializeToString,
            identity__service__pb2.BatchUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.IdentityService/GetUserByEmail',
            identity__service__pb2.UserByEmailRequest.SerializeToString,
            identity__service__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
