# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'identity_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16identity_service.proto\x12\x08identity\"V\n\x08UserItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x13\n\x0bpicture_url\x18\x05 \x01(\t\"$\n\x10\x42\x61tchUserRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\t\"6\n\x11\x42\x61tchUserResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.identity.UserItem\"#\n\x12UserByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"?\n\x0cUserResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12 \n\x04user\x18\x02 \x01(\x0b\x32\x12.identity.UserItem2\xa3\x01\n\x0fIdentityService\x12H\n\rGetUsersBatch\x12\x1a.identity.BatchUserRequest\x1a\x1b.identity.BatchUserResponse\x12\x46\n\x0eGetUserByEmail\x12\x1c.identity.UserByEmailRequest\x1a\x16.identity.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identity_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERITEM']._serialized_start=36
  _globals['_USERITEM']._serialized_end=122
  _globals['_BATCHUSERREQUEST']._serialized_start=124
  _globals['_BATCHUSERREQUEST']._serialized_end=160
  _globals['_BATCHUSERRESPONSE']._serialized_start=162
  _globals['_BATCHUSERRESPONSE']._serialized_end=216
  _globals['_USERBYEMAILREQUEST']._serialized_start=218
  _globals['_USERBYEMAILREQUEST']._serialized_end=253
  _globals['_USERRESPONSE']._serialized_start=255
  _globals['_USERRESPONSE']._serialized_end=318
  _globals['_IDENTITYSERVICE']._serialized_start=321
  _globals['_IDENTITYSERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
