from enum import Enum


class ProcessingJobType(str, Enum):
    VALIDATE = "VALIDATE"
    VALIDATION = "VALIDATE"
    UPLOAD_DRIVE = "UPLOAD_DRIVE"
    SPLIT_PDF = "SPLIT_PDF"
    PARSE_DOCUMENT = "PARSE_DOCUMENT"
    PARSE_DOCUMENT_PART = "PARSE_DOCUMENT_PART"
    MERGE_MARKDOWN = "MERGE_MARKDOWN"
    NORMALIZE_MARKDOWN = "NORMALIZE_MARKDOWN"
    DOWNLOAD = "DOWNLOAD"
    ANALYZE_MARKDOWN = "ANALYZE_MARKDOWN"
    GENERATE_CHUNKS = "GENERATE_CHUNKS"
    VALIDATE_CHUNKS = "VALIDATE_CHUNKS"
    SAVE_CHUNKS = "SAVE_CHUNKS"


class ProcessingStatus(str, Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
