server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native

  cloud:
    config:
      server:
        resolve-placeholders: true
        native:
          # Search inside src/main/resources/config/ for shared service configs
          search-locations: classpath:/config/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
